- name: Gather distribution facts
  ansible.builtin.setup:
    gather_subset: distribution_version

- name: Gather dpkg architecture
  shell: dpkg --print-architecture
  changed_when: false
  register: dpkg_architecture

- name: Copy docker apt key
  become: true
  ansible.builtin.copy:
    src: docker.asc
    dest: /etc/apt/keyrings/docker.asc
    owner: root
    group: root
    mode: u=rw,go=r
  register: add_docker_apt_key

- name: Add docker apt repository
  become: true
  ansible.builtin.copy:
    content: >
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: u=rw,go=r
  register: add_docker_apt_repository

- name: Install docker
  become: true
  ansible.builtin.apt:
    update_cache: "{{ add_docker_apt_key is changed or add_docker_apt_repository is changed }}"
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present